FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.9

ENV SUPABASE_URL=""
ENV SUPABASE_SERVICE_KEY=""

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip install --no-cache-dir supabase
RUN pip install --no-cache-dir python-dotenv
RUN pip install --no-cache-dir -r requirements.txt

COPY lambda_function.py .

CMD ["lambda_function.lambda_handler"]